<template>
  <div :style="{ overflowX: 'auto' }">
    <table>
      <tr>
        <th>{{ $t("rank") }}</th>
        <th>{{ $t("user") }}</th>
        <th>{{ $t("date") }}</th>
        <th>{{ $t("multiplier") }}</th>
        <th>{{ $t("bet") }}</th>
        <th>{{ $t("payout") }}</th>
      </tr>
      <tr>
        <td>
          <div>
            <img
              src="/png/mini/plinko/reward1.svg"
              alt="Image"
              width="20"
              height="21"
            >
          </div>
        </td>
        <td>
          <div>Los</div>
        </td>
        <td>
          <div>2023年11月22日</div>
        </td>
        <td>
          <div>
            2999.400119...
            <img
              src="/png/mini/plinko/crypto1.svg"
              alt="Image"
              width="14"
              height="14"
            >
          </div>
        </td>
        <td>
          <div>1,000x</div>
        </td>
        <td>
          <div>
            2999.400119...
            <img
              src="/png/mini/plinko/crypto1.svg"
              alt="Image"
              width="14"
              height="14"
            >
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div>
            <img
              src="/png/mini/plinko/reward2.svg"
              alt="Image"
              width="20"
              height="21"
            >
          </div>
        </td>
        <td>
          <div>
            <img src="/png/mini/plinko/cap.svg" alt="Image" width="14" height="14">
            隐身
          </div>
        </td>
        <td>
          <div>2023年9月24日</div>
        </td>
        <td>
          <div>
            1.411109923
            <img
              src="/png/mini/plinko/crypto2.svg"
              alt="Image"
              width="14"
              height="14"
            >
          </div>
        </td>
        <td>
          <div>1,000x</div>
        </td>
        <td>
          <div>
            1880.4010119...
            <img
              src="/png/mini/plinko/crypto2.svg"
              alt="Image"
              width="14"
              height="14"
            >
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div>
            <img
              src="/png/mini/plinko/reward3.svg"
              alt="Image"
              width="20"
              height="21"
            >
          </div>
        </td>
        <td>
          <div>Los</div>
        </td>
        <td>
          <div>2023年11月22日</div>
        </td>
        <td>
          <div>
            2999.400119...
            <img
              src="/png/mini/plinko/crypto1.svg"
              alt="Image"
              width="14"
              height="14"
            >
          </div>
        </td>
        <td>
          <div>1,000x</div>
        </td>
        <td>
          <div>
            2999.400119...
            <img
              src="/png/mini/plinko/crypto1.svg"
              alt="Image"
              width="14"
              height="14"
            >
          </div>
        </td>
      </tr>
    </table>
  </div>
</template>

<style scoped>
@import "../../assets/css/bigreward.css";
</style>
