/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppDemoCard: typeof import('./components/AppDemoCard.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseDivider: typeof import('./components/BaseDivider.vue')['default']
    BaseEmpty: typeof import('./components/BaseEmpty.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    BaseLoading: typeof import('./components/BaseLoading.vue')['default']
    BaseNotify: typeof import('./components/BaseNotify.vue')['default']
    BaseRadio: typeof import('./components/BaseRadio.vue')['default']
    BaseRadioGroup: typeof import('./components/BaseRadioGroup.vue')['default']
    BaseSwitch: typeof import('./components/BaseSwitch.vue')['default']
    R: typeof import('./components/R.md')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
