/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContent: typeof import('./components/AppContent.vue')['default']
    AppDemoCard: typeof import('./components/AppDemoCard.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLeftSidebar: typeof import('./components/AppLeftSidebar.vue')['default']
    AppLeftSidebarTiny: typeof import('./components/AppLeftSidebarTiny.vue')['default']
    AppSidebarBig: typeof import('./components/AppSidebarBig.vue')['default']
    AppSidebarSmall: typeof import('./components/AppSidebarSmall.vue')['default']
    BaseAccordion: typeof import('./components/BaseAccordion.vue')['default']
    BaseAspectRatio: typeof import('./components/BaseAspectRatio.vue')['default']
    BaseBadge: typeof import('./components/BaseBadge.vue')['default']
    BaseBirthDay: typeof import('./components/BaseBirthDay.vue')['default']
    BaseBirthDayInput: typeof import('./components/BaseBirthDayInput.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseCheckBox: typeof import('./components/BaseCheckBox.vue')['default']
    BaseDialog: typeof import('./components/BaseDialog.vue')['default']
    BaseDivider: typeof import('./components/BaseDivider.vue')['default']
    BaseDragDialog: typeof import('./components/BaseDragDialog.vue')['default']
    BaseEmpty: typeof import('./components/BaseEmpty.vue')['default']
    BaseGameItem: typeof import('./components/BaseGameItem.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    BaseImage: typeof import('./components/BaseImage.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseInputBirthday: typeof import('./components/BaseInputBirthday.vue')['default']
    BaseInputBirthDay: typeof import('./components/BaseInputBirthDay.vue')['default']
    BaseList: typeof import('./components/BaseList.vue')['default']
    BaseLoading: typeof import('./components/BaseLoading.vue')['default']
    BaseLogo: typeof import('./components/BaseLogo.vue')['default']
    BaseNotify: typeof import('./components/BaseNotify.vue')['default']
    BaseNumericKeypad: typeof import('./components/BaseNumericKeypad.vue')['default']
    BaseProgress: typeof import('./components/BaseProgress.vue')['default']
    BaseRadio: typeof import('./components/BaseRadio.vue')['default']
    BaseRadioGroup: typeof import('./components/BaseRadioGroup.vue')['default']
    BaseSearch: typeof import('./components/BaseSearch.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    BaseSkeleton: typeof import('./components/BaseSkeleton.vue')['default']
    BaseSwitch: typeof import('./components/BaseSwitch.vue')['default']
    BaseTab: typeof import('./components/BaseTab.vue')['default']
    BaseTable: typeof import('./components/BaseTable.vue')['default']
    BaseTag: typeof import('./components/BaseTag.vue')['default']
    BaseUpload: typeof import('./components/BaseUpload.vue')['default']
    BaseWallet: typeof import('./components/BaseWallet.vue')['default']
    R: typeof import('./components/R.md')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
